name: MDRMF
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - joblib
  - lightgbm
  - matplotlib
  - numpy
  - pandas
  - pykwalify
  - PyYAML
  - rdkit
  - scipy
  - pip:
    - MDRMF
    - scikit_learn