- Protocol_name: structural_biology_presentation_140k_05p

- save_models: False
- save_datasets: False
- save_nothing: False

- unique_initial_sample:
    sample_size: 10
    nudging: [5, 1400]


- Experiment:
    name: top100_of_140k_0.5p
    replicate: 2

    dataset: datasets/DTP_CDDD_fix2.pkl

    model:
      name: RFModeller
      iterations: 15
      acquisition_size: 20
      acquisition_method: greedy

    metrics:
      names: [top-k, top-k-acquired]
      k: [100]


# - Experiment:
#     name: top1p_of_140k
#     replicate: 10

#     dataset: datasets/DTP_CDDD_fix2.pkl

#     model:
#       name: RFModeller
#       iterations: 5
#       acquisition_size: 20
#       acquisition_method: greedy

#     metrics:
#       names: [top-k, top-k-acquired]
#       k: [1400]


# - Experiment:
#     name: top5p_of_140k
#     replicate: 10

#     dataset: datasets/DTP_CDDD_fix2.pkl

#     model:
#       name: RFModeller
#       iterations: 5
#       acquisition_size: 20
#       acquisition_method: greedy

#     metrics:
#       names: [top-k, top-k-acquired]
#       k: [7000]