- Protocol_name: test protocol # Use this to define a unique protocol name, if not defined it defaults to 'protocol'

- save_models: False
- save_datasets: False
- save_nothing: True

- Experiment:
    name: Exp01
    replicate: 3

    data:
        datafile: 10K.csv
        SMILES_col: SMILES
        scores_col: r_i_docking_score
        ids_col: SMILES

    featurizer:
        name: mqn

    model:
        name: RFModeller
        iterations: 2
        initial_sample_size: 5
        acquisition_size: 5
        acquisition_method: greedy

    metrics: 
        names: [top-k, top-k-acquired]
        k: [100]